config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  get 'owner', to: 'automobiles#owner', as: :owner
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :automobiles do
    resources :bookings, only: %i[new create]
  end
  resources :bookings, only: %i[index show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/automobile.rb
CATEGORIES = ["Automóvil", "Motocicleta", "Camioneta", "Camión"]

class Automobile < ApplicationRecord
  validates :brand, :model, :year, :category, :price, :address, :km, :photo, presence: true
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?

  has_one_attached :photo

  belongs_to :user
  has_many :reviews, as: :reviewable
  has_many :bookings, dependent: :destroy

  include PgSearch::Model
  pg_search_scope :search_by_automobiles_model_and_brand, against: [:model, :brand], using: { tsearch: { prefix: true } }

  pg_search_scope :search_by_automobiles_km, against: :km, using: { tsearch: { prefix: true } }

  pg_search_scope :search_by_automobiles_price, against: :price, using: { tsearch: { prefix: true } }

  def self.search(args)
    location_query = args[:location]
    price_query = args[:price]
    km_query = args[:km]
    model_brand_query = args[:model_brand]
    results = []

    if location_query
      by_location = Automobile.near(location_query)
      by_location.each { |instance| results << instance }
    end

    if price_query
      by_price = Automobile.search_by_automobiles_price(price_query)
      by_price.each { |instance| results << instance }
    end

    if km_query
      by_km = Automobile.search_by_automobiles_km(km_query)
      by_km.each { |instance| results << instance }
    end

    if model_brand_query
      by_model_brand = Automobile.search_by_automobiles_model_and_brand(model_brand_query)
      by_model_brand.each { |instance| results << instance }
    end

    return results
    # combine the results of by_location & by_model & 
  end
end

# match = Automobile.search("aa").with_pg_search_highlight (now i have available the .pg_search_highlight attribute)

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :automobile

  validates :starting_date, :finish_date, presence: true
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :reviewable, polymorphic: true
  belongs_to :user
  belongs_to :booking
end

app/models/user.rb
class User < ApplicationRecord
  has_one_attached :photo
  has_many :bookings, dependent: :destroy
  has_many :automobiles, dependent: :destroy
  has_many :reviews, as: :reviewable
  has_many :performed_reviews, class_name: "Review", foreign_key: "user_id" 
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:photo, :birth_date, :phone_number])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:photo])
  end
end

app/controllers/automobiles_controller.rb
class AutomobilesController < ApplicationController
  skip_before_action :authenticate_user!, only: :index
  def index
    if params[:location_query].present? || params[:price_query].present? || params[:km_query].present? || params[:model_brand_query].present?
      @automobiles = Automobile.geocoded.search({
        location: params[:location_query],
        price: params[:price_query],
        km: params[:km_query],
        model_brand: params[:model_brand_query],
        })
    else
      @automobiles = Automobile.geocoded
    end

    @markers = @automobiles.map do |automobile|
      {
        lat: automobile.latitude,
        lng: automobile.longitude,
        infoWindow: render_to_string(partial: "info_window", locals: { automobile: automobile })
      }
    end
  end

  def show
    @booking = Booking.new
    @automobile = Automobile.find(params[:id])
  end

  def new
    @automobile = Automobile.new
  end

  def create
    @automobile = Automobile.new(automobile_params)
    @automobile.user = current_user
    if @automobile.save
      redirect_to owner_path
    else
      render :new
    end
  end

  def edit
    @automobile = Automobile.find(params[:id])
  end

  def update
    @automobile = Automobile.find(params[:id])
    if @automobile.update(automobile_params)
      redirect_to automobile_path(@automobile)
    else
      render :edit
    end
  end

  def owner
    @automobiles = Automobile.where(user_id: current_user.id)
  end

  def destroy
    @automobile = Automobile.find(params[:id])
    @automobile.destroy

    redirect_to owner_path
  end

  private

  def automobile_params
    params.require(:automobile).permit(:brand, :model, :year, :km, :category, :price, :photo, :address)
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def index
    @bookings = Booking.where(user_id: current_user.id)
  end

  def show
    @booking = Booking.find(params[:id])
  end

  def create
    @booking = Booking.new(booking_params)
    @automobile = Automobile.find(params[:automobile_id])
    @booking.user = current_user
    @booking.automobile = @automobile
    if @booking.save
      redirect_to bookings_path
    else
      render 'automobiles/show'
    end
  end

  private

  def booking_params
    params.require(:booking).permit(:starting_date, :finish_date, :total_price)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home
  
  def home
    @automobiles = Automobile.limit(3)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/automobiles/_info_window.html.erb
<%= link_to automobile_path(automobile) do %>
  <%= cl_image_tag automobile.photo.key, crop: :fill %>
  <div class="popup-infos">
    <h2 class="text-center"><%= automobile.brand %> <%= automobile.model %></h2>
    <div class="popup-info">
      <h3>Only for $<%= automobile.price %>/day</h3>
      <div>
        <p><%= automobile.km %>km</p>
        <p>Model: <%= automobile.year %></p>
      </div>
    </div>
  </div>
<% end %>

app/views/automobiles/edit.html.erb
<div class="container">
  <h1 class="text-center">Edit your car</h1>
  <%= simple_form_for @automobile do |f| %>
  <%= f.input :model %>
  <%= f.input :brand %>
  <%= f.input :km %>
  <%= f.input :year %>
  <%= f.input :price %>
  <%= f.input :category, collection: CATEGORIES %>
  <%= f.input :photo, as: :file %>
  <%= f.button :submit, class: 'btn btn-primary mb-3' %>
<% end %>

<%= link_to "Go back", owner_path, class: 'btn btn-primary' %>
</div>

app/views/automobiles/index.html.erb
<!-- CARDS -->
<div class="d-flex container-index w-100 p-3">
  <div class="container">
    <h3 class="text-left">Compare rental car deals to find the right one!</h3>
    <div class="search-bar mb-4 text-center">
      <%= form_tag automobiles_path, method: :get, class: 'row col-12 ps-2 text-center' do %>
        <%= text_field_tag :location_query, params[:location_query], id: "location", class: "form-control col-6 col-md-3", placeholder: "Location" %>
        <%= text_field_tag :price_query, params[:price_query], class: "form-control col-6 col-md-3", placeholder: "Price" %>
        <%= text_field_tag :km_query, params[:km_query], class: "form-control col-6 col-md-3", placeholder: "Km" %>
        <%= text_field_tag :model_brand_query, params[:model_brand_query], class: "form-control col-6 col-md-3", placeholder: "Model/Brand" %>
        <%= submit_tag "Search", class: "mt-2 col-12 fas fa-search btn btn-primary" %>
      <% end %>
    </div>
    <div class="row">
      <% @automobiles.each do |automobile| %>
      <div class="col-12 col-lg-6">
        <div class="card-trip">     
          <%= cl_image_tag automobile.photo.key %>
          <div class="card-trip-infos">
            <div>
              <%= link_to automobile_path(automobile) do %>
              <h2><%= automobile.brand %> <%= automobile.model %></h2>
              <% end %>
              <p class="pt-2"><%= "#{automobile.year} | #{automobile.km} Km" %></p>
            </div>
            <h2 class="card-trip-pricing">$<%= "#{automobile.price} daily"%></h2>
            <%= cl_image_tag automobile.user.photo.key, class: 'card-trip-user avatar-bordered' %>
          </div>
        </div>
      </div>
    <% end %>
    </div>
  </div>
  <div id="map" class="col-6" style="position: sticky; top: 0; height: 100vh;" data-markers="<%= @markers.to_json %>" data-mapbox-api-key="<%= ENV["MAPBOX_API_KEY"] %>"> </div>
</div>

app/views/automobiles/new.html.erb
<div class="container">
<h1 class="text-center my-3">Create a car!</h1>
<div class="d-flex">
  <div class="auto-new-form w-50">
      <%= simple_form_for @automobile do |f| %>
      <%= f.input :model %>
      <%= f.input :brand %>
      <%= f.input :km %>
      <%= f.input :year %>
      <%= f.input :price %>
      <%= f.input :address %>
      <%= f.input :category, collection: CATEGORIES %>
      <%= f.input :photo, as: :file %>
      <%= f.button :submit, class: 'btn btn-primary' %>
    <% end %>
    <%= link_to "Go back", owner_path, class: "btn btn-primary my-3" %>
  </div>
  
  <img src="https://images.unsplash.com/photo-1514316454349-750a7fd3da3a?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=634&q=80" class="car-new-image" alt="car">
  
</div>
</div>

app/views/automobiles/owner.html.erb
<div class="container text-center">
  <h1 class="mt-4">Manage your cars</h1>
  <div class="d-flex justify-content-center">
    <div class="row my-3">
      <div class="col-12">
        <% if @automobiles.empty? %>
        <div class="d-flex flex-column">
          <p>Don't have a car yet? Not a problem! It just takes 2 minutes!</p>
          <%= link_to "Create your first car", new_automobile_path, class: 'btn btn-primary' %>
        </div>
        <% else %>
          <div class="col-12">
            <%= link_to "Add a new car", new_automobile_path, class: 'btn btn-primary mt-3' %>
          </div>
          <% @automobiles.each do |automobile| %>
            <div class="card-booking my-4">
              <%= cl_image_tag automobile.photo.key, height: 250 %>
              <h2 class="py-3 brand-model"><%= automobile.brand %> <%= automobile.model %></h2>
              <div class="card-booking-infos">
                <div class="automobile-info">
                  <p>Year: <%= automobile.year %></p>
                  <p><%= automobile.km %> km</p>
                </div>
                <div class="booking-info">
                  <p><%= "$#{automobile.price} daily" %></p>
                </div>
                <div class="fechas">
                  <%= link_to "Edit", edit_automobile_path(automobile), class: 'btn btn-primary' %>
                  <%= link_to "Delete", automobile_path(automobile), class: 'btn btn-primary', method: :delete, data: { confirm: "Are you sure?" } %>
                </div>  
              </div>
            </div>
            <% end %>
          </div>
        <% end %>
    </div>
  </div>
</div>

app/views/automobiles/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-12">
      <div class="card-trip card-trip-infos my-3 rounded">
        <div class="show-header">
          <div class="d-flex align-items-center" id="car-name">
            <%= @automobile.model %> <%= @automobile.brand %>
          </div>
          <div class="d-flex align-items-center" id="owner-info">
            <div id="owner-name"><%= @automobile.user.full_name %></div>
            <% if @automobile.user.photo.attached? %>
              <%= cl_image_tag @automobile.user.photo.key, class: "avatar-round" %>
            <% else %>
              <img src="app/assets/images/photo_placeholder.png" alt="user" class="avatar-round">
            <% end %>
          </div> 
        </div>    
      </div>
      
      <div class="car-info">
        <%= cl_image_tag @automobile.photo.key, class: "car-img" %>        
      </div>
      <table class="table col-8 mt-3">
        <thead>
          <tr>
            <th>Model:</th>
            <th>Brand:</th>
            <th>Category:</th>
            <th>Year:</th>
            <th>Km:</th>              
          </tr>          
        </thead>
        <tbody>
          <td><%= @automobile.model %></td>
          <td><%= @automobile.brand %></td>
          <td><%= @automobile.category %></td>
          <td><%= @automobile.year %></td>
          <td><%= @automobile.km %></td>            
        </tbody>
      </table>
      <div class="book-card col-5 offset-8 p-3">
        <div>
          <%= simple_form_for [ @automobile, @booking ] do |f| %>
            <h5>Choose when and just enjoy your car!</h5>
            <div class="form">
              <%= f.input :starting_date, as: :string, required: true, error: 'Starting date is mandatory, please specify one', input_html: {class: "datepicker", id: "start_date"} %>
              <%= f.input :finish_date, as: :string, required: true, error: 'Finishing date is mandatory, please specify one', input_html: {class: "datepicker", id: "finish_date"} %>
              <%= f.input :total_price, :as => :hidden, :input_html => { :value => "", id: "form_total_price" } %> 
            </div>              
            <div class="book-card-footer">
              <h6><strong>Total price:</strong></h6><span id="total_price" data-price="<%= @automobile.price %>"><%= @automobile.price %></span>
              <%= f.submit "Book now", class: "btn btn-primary", id: "new_booking_submit" %>
            </div> 
          <% end %>
        </div>
      </div>
      <div id="link-1">
        <%= link_to "Back to cars", automobiles_path, class: "btn btn-primary" %>
      </div>
    </div>
  </div>
</div>

app/views/bookings/index.html.erb
<div class="container text-center">
  <h1 class="mt-4">Explore all your bookings</h1>
  <div class="d-flex justify-content-center">
    <div class="row my-3">
      <div class="col-12">
      <% if @bookings.empty? %>
        <%= link_to "Book now!", automobiles_path, class: 'btn btn-primary' %>
      <% else %>
        <% @bookings.each do |booking| %>
          <div class="card-booking my-4">
            <%= cl_image_tag booking.automobile.photo.key, height: 250 %>
            <h2 class="py-3 brand-model"><%= booking.automobile.brand %> <%= booking.automobile.model %></h2>
            <div class="card-booking-infos">
              <div class="automobile-info">
                <p>Year: <%= booking.automobile.year %></p>
                <p><%= booking.automobile.km %> km</p>
              </div>
              <div class="booking-info">
                <!--<p>Booking status: <%= booking.status %></p>-->
                <p>Paid: <%= booking.paid ? "Si" : "No" %></p>
                <p>Total price: $<%= booking.total_price %></p>
              </div>
              <div class="fechas">
                <p>From: <%= booking.starting_date %></p>
                <p>To: <%= booking.finish_date %></p>
              </div>  
            </div>
          </div>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/bookings/show.html.erb
<div class="container text-center">
  <h1 class="">Booking details</h1>
  <div class="d-flex justify-content-center">
    <div class="card-booking">
      <%= cl_image_tag @booking.automobile.photo.key, crop: :fill %>
      <h2 class="py-3 bg-secondary"><%= @booking.automobile.brand %> <%= @booking.automobile.model %></h2>
      <div class="card-booking-infos">
        <div class="automobile-info">
          <p>Year: <%= @booking.automobile.year %></p>
          <p><%= @booking.automobile.km %> km</p>
        </div>
        <div class="booking-info">
          <p>Booking status: <%= @booking.status %></p>
          <p>Paid: <%= @booking.paid ? "Si" : "No" %></p>
          <p>Total price: <%= @booking.total_price %></p>
        </div>
        <div class="fechas">
          <p>From: <%= @booking.starting_date %></p>
          <p>To: <%= @booking.finish_date %></p>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EasyTravel</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_pack_tag 'application' %>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <div class="page-container">
      <%= render 'shared/navbar' %>

      <div class="content-wrap">
        
        <%= render 'shared/flashes' %>
    
        <%= yield %>
      </div>
      <%= render 'shared/footer' %>
    </div>
  </body>
</html>

app/views/pages/home.html.erb
<!-- BANNER -->
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.unsplash.com/photo-1568605117036-5fe5e7bab0b7?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=1050&q=80);">
  <div class="container-search">
    <div class="search col-10 col-md-8 col-lg-6">
      <h1>Drive anywhere, at the best price</h1>
      <p>Compare rental car deals to find the right one!</p>
      <div class="search-bar mb-4 text-center">
      <%= form_tag automobiles_path, method: :get, class: 'row col-12 ps-2 text-center' do %>
        <%= text_field_tag :location_query, params[:location_query], id: "location", class: "form-control col-6 col-md-3", placeholder: "Location" %>
        <%= text_field_tag :price_query, params[:price_query], class: "form-control col-6 col-md-3", placeholder: "Price" %>
        <%= text_field_tag :km_query, params[:km_query], class: "form-control col-6 col-md-3", placeholder: "Km" %>
        <%= text_field_tag :model_brand_query, params[:model_brand_query], class: "form-control col-6 col-md-3", placeholder: "Model/Brand" %>
        <%= submit_tag "Search", class: "mt-2 col-12 fas fa-search btn btn-primary" %>
      <% end %>
    </div>
    </div>
  </div>
</div>

<!-- CARDS -->
<div class="container-reviews">
  <h1 class="mt-4 text-left">Explore the most popular cars</h1>
  <p class="text-left mt-2 mb-4">Over 1,000 user reviews, with an average rating of 4.8 out of 5 stars.</p>
  <div class="row">
    <% @automobiles.each do |automobile| %>
    <div class="col-12 col-md-6 col-lg-4 col-xl-3 col-xxl-2">
      <div class="card-trip">     
        <%= cl_image_tag automobile.photo.key %>
        <div class="card-trip-infos">
          <div>
            <%= link_to automobile_path(automobile) do %>
            <h2><%= automobile.brand %> <%= automobile.model %></h2>
            <% end %>
            <p class="pt-2"><%= "#{automobile.year} | #{automobile.km} Km" %></p>
          </div>
          <h2 class="card-trip-pricing">$<%= "#{automobile.price} daily"%></h2>
          <%= cl_image_tag automobile.user.photo.key, class: 'card-trip-user avatar-bordered' %>
        </div>
      </div>
    </div>
    <% end %>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">        
    <a href="#">Contact</a>
    <a href="#">Privacy</a>
    <a href="#">Terms</a>
    <a href="#">Help/FAQ</a>      
  </div>
  <div class="footer-owners">
    Made by Ariel Waisburg, Eric Hoare, Lucía Pérez Diez and Santiago Castillo
  </div>
  <div class="footer-social-media">
    <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-instagram-square"></i></a>
    <a href="#"><i class="fab fa-youtube"></i></a>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon d-flex bd-highlight">
  <div class="d-flex align-items-center">
    <%= link_to root_path, class: "navbar-brand m-0 bd-highlight" do %>
      <%= image_tag "car_logo.png", style: "zoom: 150%" %>
    <% end %>
    <div id="navbar-title" class="p-2 bd-highlight">
      <%= link_to "EasyTravel", root_path, class: "nav-link" %>
    </div>
  </div>
  <!-- Para que es esto? -->
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active align-items-center">
          <%= link_to "Rent your car", owner_path, class: "nav-link" %>
        </li>
        <li class="nav-item dropdown ms-auto pt-3 px-2 bd-highlight align-items-center">
          <div class="nav-item dropdown" id="dropdown-section">
            <% if current_user.photo.attached? %>
              <%= cl_image_tag current_user.photo.key, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <% else %>
              <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <% end %>
            <div style= "height: 20px; width: 100%"></div>
            <div class="dropdown-menu dropdown-menu-right m-0" aria-labelledby="navbarDropdown">
              <%= link_to "Bookings", bookings_path, class: "dropdown-item" %>
              <%= link_to "Cars", owner_path, class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
            </div>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Rent your car", new_user_registration_path, class: "nav-link" %>
          <%= link_to "Login", new_user_session_path, class: "simple-hover" %>
          <%= link_to "Sign up", new_user_registration_path, class: "simple-hover" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>